#!/bin/bash

echo "=========================================="
echo "  KBZ Pay QR Code Setup"
echo "=========================================="
echo ""
echo "I can see your perfectly cropped QR code!"
echo ""
echo "Now follow these steps:"
echo ""
echo "1. Save that QR code image you just showed me"
echo "   (Right-click → Save Image As...)"
echo ""
echo "2. Name it: kbzpay-qr.png"
echo ""
echo "3. Save it to this location:"
echo "   /Users/aunghtet/Desktop/projects/lonemalaypos/public/"
echo ""
echo "OR simply drag and drop it into the 'public' folder"
echo ""
echo "=========================================="
echo ""
echo "After saving, run this command to verify:"
echo ""
echo "  ls -lh public/kbzpay-qr.png"
echo ""
echo "Then refresh your app and the QR code will appear!"
echo ""
echo "=========================================="

